project_name: falcosidekick-ui
builds:
  - id: "falcosidekick-ui"
    goos:
      - linux
    goarch:
      - amd64
    main: main.go
    env:
      - CGO_ENABLED=0
    binary: falcosidekick-ui

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "falcosecurity/falcosidekick-ui:latest"
      - "falcosecurity/falcosidekick-ui:{{ .Version }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - static
      - main.go
      - go.mod
      - go.sum
      - Makefile
      - LICENSE

release:
  github:
  prerelease: auto

dist: dist-goreleaser
