project_name: falcosidekick-ui

before:
  hooks:
  - go mod tidy
  - make frontend

builds:
  - id: "falcosidekick-ui"
    goos:
      - linux
    goarch:
      - amd64
    main: main.go
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    binary: falcosidekick-ui

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "falcosecurity/falcosidekick-ui:latest"
      - "falcosecurity/falcosidekick-ui:{{ .Version }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - frontend/dist
      - LICENSE

release:
  github:
    owner: falcosecurity
    name: falcosidekick-ui
  prerelease: auto

dist: dist-goreleaser
