project_name: falcosidekick-ui
version: 2

env:
  - GO111MODULE=on
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - BUILDX_PLATFORMS=linux/amd64,linux/arm64,linux/arm/v7
  - COSIGN_YES=true

snapshot:
  version_template: 'latest'

checksum:
  name_template: 'checksums.txt'

before:
  hooks:
  - go mod tidy
  - make frontend

sboms:
  - artifacts: archive

builds:
  - id: "falcosidekick-ui"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    main: main.go
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    binary: falcosidekick-ui

dockers_v2:
  - dockerfile: Dockerfile
    images:
      - "falcosecurity/falcosidekick-ui"
      - "public.ecr.aws/falcosecurity/falcosidekick-ui"
    tags:
      - "stable"
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - frontend/dist
      - LICENSE

signs:
  - id: falcosidekick-ui
    signature: "${artifact}.sigstore.json"
    cmd: cosign
    args: ["sign-blob", "--bundle", "${signature}", "${artifact}"]
    artifacts: archive
  - id: checksum
    signature: "${artifact}.sigstore.json"
    cmd: cosign
    args: ["sign-blob", "--bundle", "${signature}", "${artifact}"]
    artifacts: checksum

docker_signs:
  - id: falcosidekick-ui
    cmd: cosign
    args: ["sign", "--recursive", "${artifact}"]
    artifacts: manifests
    output: true

release:
  github:
    owner: falcosecurity
    name: falcosidekick-ui
  prerelease: auto

dist: dist-goreleaser
