version: 2.1
executors:
  default:
    docker:
      - image: cimg/go:1.18
  docker-build:
    docker:
      - image: docker:stable

install_buildx: &install_buildx
  name: Install Docker buildx
  command: |
    mkdir -p ~/.docker/cli-plugins
    curl -sSL -o ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64
    chmod a+x ~/.docker/cli-plugins/docker-buildx

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make lint

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make test

  build-image:
    docker:
      - image: cimg/base:current
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: *install_buildx
      - run: make build-image

  build-push-main:
    docker:
      - image: cimg/base:current
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: *install_buildx
      - run: make build-image
      - run:
          command: |
            echo ${DOCKERHUB_SECRET} | docker login -u ${DOCKERHUB_USER} --password-stdin
            docker push falcosecurity/falcosidekick-ui:latest

  build-push-ecr:
    docker:
      - image: cimg/base:current
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: *install_buildx
      - run:
          command: |
            apk add --update make bash
            make build-image
      - run:
          command: |
            docker tag falcosecurity/falcosidekick-ui:latest \
              public.ecr.aws/falcosecurity/falcosidekick-ui:latest
      - run:
          command: |
            apk add --update groff less py-pip
            pip install awscli
            aws ecr-public get-login-password --region us-east-1 | \
              docker login --username AWS --password-stdin public.ecr.aws/falcosecurity
            docker push public.ecr.aws/falcosecurity/falcosidekick-ui:latest

  release:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: *install_buildx
      - run:
          name: Prepare env
          command: |
            echo ${DOCKERHUB_SECRET} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  main:
    jobs:
      - test
      - lint
      - build-image:
          requires:
            - test
            - lint
          filters:
            branches:
              ignore: master
      - build-push-main:
          context: falco
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
      - build-push-ecr:
          context: test-infra
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
      - release:
          context: falco
          requires:
            - test
            - lint
            - build-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
